# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d549113e41cdedc76385c70c901f5d15605a8f5461ef2a4f8c02665650c6b8a4fa66bcaaf8dc2aca15e429dcf23d71d1ba316ec7f147b81e703d161df5126f08

test:
  secret_key_base: b67464b87582d93a2df4ec4f1aae8355b4628b4a200f4cc8edb8e6fe1c0ce45b120fd12cb0295d2d4d1b1e9a6f128ad3b8623b28efc056daa0e1a34ed923e7fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
